version: '3'

services:
  app:
    container_name: encoder-de-videos
    build: .
    volumes:
      - .:/go/src/

  rabbit-encoder-de-videos:
    container_name: rabbit-encoder-de-videos
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "15672:15672"
      - "5672:5672"