version: '3'

services:
  app:
    container_name: encoder-de-videos
    build: .
    volumes:
      - .:/go/src/

  postgres-encoder-de-videos:
    container_name: postgres-encoder-de-videos
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: encoder-de-videos
    ports:
      - "5432:5432"

  rabbit-encoder-de-videos:
    container_name: rabbit-encoder-de-videos
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: SWQOKODSQALRPCLNMEQG
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbit-encoder-de-videos:/var/lib/rabbitmq/

volumes:
  rabbit-encoder-de-videos: